// 폼 입력 길이 제한 (백엔드 schema 한도와 동일하게 유지)
export const VALIDATION_LIMITS = {
  ACCOUNT_NAME_MAX: 50,
  ASSET_NAME_MAX: 100,
  EXCHANGE_MAX: 50,
  TRADE_FREE_TEXT_MAX: 5000,
  CUSTOM_TAG_MAX_LEN: 20,
  CUSTOM_TAG_MAX_COUNT: 10,
} as const;

export const TRADE_FREE_TEXT_ERROR = `${VALIDATION_LIMITS.TRADE_FREE_TEXT_MAX}자 이내로 입력해주세요.`;
